name: Validation tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: knowledge-graph

jobs:
  validation-tests:
    runs-on: ubuntu-latest
    name: Validation tests
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: knowledge-graph

    - name: Verify content
      run: |
        ./build/validate.sh
